name: habitual
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    production:
      app:
        name: "Habitual"
      android:
        applicationId: "com.suzan.habitual"
      ios:
        bundleId: "com.suzan.habitual"

    sandbox:
      app:
        name: "Habitual - Sandbox"
      android:
        applicationId: "com.suzan.habitual-sandbox"
      ios:
        bundleId: "com.suzan.habitual-sandbox"

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Logger
  logger: ^1.1.0

  # Bloc
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.1.0

  # Data Class
  json_annotation: ^4.4.0
  equatable: ^2.0.3

  # Functional Programming
  dartz: ^0.10.1

  # Dependency Injection
  injectable: ^1.5.3
  get_it: ^7.2.0

  # Router
  vrouter: ^1.2.0+21

  # Cupertino Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Flavour
  flutter_flavorizr: ^2.1.3

  json_serializable: ^6.1.6

  build_runner: ^2.1.10

  # Flutter Linting
  flutter_lints: ^1.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true